### ISSUE TITLE
не могу скачать моды на hollow knight

### ISSUE THREAD

**Issue by MEdoed500** [TheMulhima/Lumafly#104]
### Lumafly Version

v3.2.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

нет

### Expected Behaviour

хотел скачать мод и играть с ним

### Actual Behaviour

я не могу скачивать моды постоянно вылезает ошибка и не появляется папка мод в настройках игры

### Errors and Logs

Возникло исключение во время Установить API

Lumafly Version: 3.2.0.0

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера..
 ---> System.Net.Sockets.SocketException (10060): Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Lumafly.Util.HttpClientExt.DownloadBytesWithProgressAsync(HttpClient self, Uri uri, IProgress`1 progress, CancellationToken cts) in D:\a\Lumafly\Lumafly\Lumafly\Util\HttpClientExt.cs:line 22
   at Lumafly.Services.Installer.DownloadFile(String uri, Action`1 setProgress) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 589
   at Lumafly.Services.Installer._InstallApi(ValueTuple`3 manifest) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 280
   at Lumafly.Services.Installer.InstallApi() in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 257
   at Lumafly.ViewModels.ModListViewModel.<ToggleApiCommand>g__DoActionWithWithErrorHandling|106_0(Func`1 Action) in D:\a\Lumafly\Lumafly\Lumafly\ViewModels\ModListViewModel.cs:line 576

**Comment by Ruttie2006** [comment]
вы подключены к Интернету?

('are you connected to the internet?', translated using translate, so my apology for any mistakes)

**Comment by MEdoed500** [comment]
да

**Comment by MEdoed500** [comment]
yes
