### ISSUE TITLE
Microsoft.Toolkit.HighPerformance not found

### ISSUE THREAD

**Issue by 7TBZ** [TheMulhima/Lumafly#108]
### Lumafly Version

v3.2.00

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Unable to installing or uninstalling Abskoth.
Lumafly was unable to access the file in the mods folder.

Lumafly Version: 3.2.0.0

System.IO.FileNotFoundException: 
File name: 'Microsoft.Toolkit.HighPerformance, Version=7.1.0.0, Culture=neutral, PublicKeyToken=4aff67a105548ee2'
   at Lumafly.Services.Installer.ThrowIfInvalidHash(String name, ArraySegment`1 data, String modSha256)
   at Lumafly.Services.Installer._Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls)
   at Lumafly.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls)
   at Lumafly.Models.ModItem.OnInstall(IInstaller inst, Action`1 setProgress)
   at Lumafly.ViewModels.ModListViewModel.InternalModDownload(ModItem item, Func`3 downloader)

### Expected Behaviour

Unable to installing or uninstalling Abskoth.
Lumafly was unable to access the file in the mods folder.

Lumafly Version: 3.2.0.0

System.IO.FileNotFoundException: 
File name: 'Microsoft.Toolkit.HighPerformance, Version=7.1.0.0, Culture=neutral, PublicKeyToken=4aff67a105548ee2'
   at Lumafly.Services.Installer.ThrowIfInvalidHash(String name, ArraySegment`1 data, String modSha256)
   at Lumafly.Services.Installer._Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls)
   at Lumafly.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls)
   at Lumafly.Models.ModItem.OnInstall(IInstaller inst, Action`1 setProgress)
   at Lumafly.ViewModels.ModListViewModel.InternalModDownload(ModItem item, Func`3 downloader)

### Actual Behaviour

Unable to installing or uninstalling Abskoth.
Lumafly was unable to access the file in the mods folder.

Lumafly Version: 3.2.0.0

System.IO.FileNotFoundException: 
File name: 'Microsoft.Toolkit.HighPerformance, Version=7.1.0.0, Culture=neutral, PublicKeyToken=4aff67a105548ee2'
   at Lumafly.Services.Installer.ThrowIfInvalidHash(String name, ArraySegment`1 data, String modSha256)
   at Lumafly.Services.Installer._Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls)
   at Lumafly.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls)
   at Lumafly.Models.ModItem.OnInstall(IInstaller inst, Action`1 setProgress)
   at Lumafly.ViewModels.ModListViewModel.InternalModDownload(ModItem item, Func`3 downloader)

### Errors and Logs

Unable to installing or uninstalling Abskoth.
Lumafly was unable to access the file in the mods folder.

Lumafly Version: 3.2.0.0

System.IO.FileNotFoundException: 
File name: 'Microsoft.Toolkit.HighPerformance, Version=7.1.0.0, Culture=neutral, PublicKeyToken=4aff67a105548ee2'
   at Lumafly.Services.Installer.ThrowIfInvalidHash(String name, ArraySegment`1 data, String modSha256)
   at Lumafly.Services.Installer._Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls)
   at Lumafly.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls)
   at Lumafly.Models.ModItem.OnInstall(IInstaller inst, Action`1 setProgress)
   at Lumafly.ViewModels.ModListViewModel.InternalModDownload(ModItem item, Func`3 downloader)

**Comment by TheMulhima** [comment]
What version of windows do you have?

**Comment by kfish610** [comment]
I'm encountering this issue as well, Windows 11 24H2

**Comment by kfish610** [comment]
My bad, it occurred because I moved the file after launching it. Closing and relaunching fixed it. Hopefully this helps someone else with this issue.
