### ISSUE TITLE
Mods cant update? (it thinks hollowknight is open)

### ISSUE THREAD

**Issue by Funn1i** [TheMulhima/Lumafly#109]
### Lumafly Version

v3.2.0.0

### Hollow Knight Version

1.5.78.11833

### Steps to Reproduce

Attempted to update mods, got the "Hollow knight is open!" popup, i clicked yes for it to close, it didn't do anything
Next time I tried it I clicked 'no' and got the error

### Expected Behaviour

For the mods to update

### Actual Behaviour

The mods didn't update, instead getting the error (if I clicked no), or if I clicked yes nothing happened

### Errors and Logs

Unable to installing or uninstalling Custom Knight.
Lumafly was unable to access the file in the mods folder.

Lumafly Version: 3.2.0.0

System.IO.IOException: The requested operation cannot be performed on a file with a user-mapped section open. : 'D:\SteamLibrary\steamapps\common\Hollow Knight\hollow_knight_Data\Managed\Mods\Satchel\Satchel.pdb'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.Abstractions.FileStreamFactory.New(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at Lumafly.Services.Installer.ExtractToFile(ZipArchiveEntry src, String dest) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 645
   at Lumafly.Services.Installer.ExtractZip(ArraySegment`1 data, String root) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 629
   at Lumafly.Services.Installer.PlaceMod(ModItem mod, Boolean enable, String filename, ArraySegment`1 data) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 554
   at Lumafly.Services.Installer._Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 440
   at Lumafly.Services.Installer._Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 414
   at Lumafly.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 366
   at Lumafly.Models.ModItem.OnUpdate(IInstaller inst, Action`1 setProgress) in D:\a\Lumafly\Lumafly\Lumafly\Models\ModItem.cs:line 174
   at Lumafly.ViewModels.ModListViewModel.InternalModDownload(ModItem item, Func`3 downloader) in D:\a\Lumafly\Lumafly\Lumafly\ViewModels\ModListViewModel.cs:line 1019

**Comment by Ruttie2006** [comment]
I would recommend restarting your computer.

**Comment by Funn1i** [comment]
> I would recommend restarting your computer.

it worked! idk how i didn't think of this before, though i suppose i'm not the brightest eheh
thanks!
