### ISSUE TITLE
Erro de Conexão

### ISSUE THREAD

**Issue by RICK697** [TheMulhima/Lumafly#112]
### Lumafly Version

V 3.2.0.0

### Hollow Knight Version

v1,5,78,11833

### Steps to Reproduce

Revisar o que foi feito nesta versão, mas o detalhe que tem em incomum é que eu estou Utilizando uma versão Crekeada do jogo mas, eu nao tive esse problema nas versões anteriores do instalador. Não sei se o caso desse problema e a questão de eu está Utilizando um celular como roteador via a cabo
![Anotação 2024-06-07 162940](https://github.com/TheMulhima/Lumafly/assets/172075973/615fa620-8163-40a2-85f2-d0de442dec71)

### Expected Behaviour

que nao mé deparaçe com esse tipo de erro

### Actual Behaviour

Entrei dentro do Lumafly e nao consegui instalar nenhum mod

### Errors and Logs

Uma exceção ocorrer enquanto Instalar API

Lumafly Version: 3.2.0.0

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Lumafly.Util.HttpClientExt.DownloadBytesWithProgressAsync(HttpClient self, Uri uri, IProgress`1 progress, CancellationToken cts) in D:\a\Lumafly\Lumafly\Lumafly\Util\HttpClientExt.cs:line 22
   at Lumafly.Services.Installer.DownloadFile(String uri, Action`1 setProgress) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 589
   at Lumafly.Services.Installer._InstallApi(ValueTuple`3 manifest) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 280
   at Lumafly.Services.Installer.InstallApi() in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 257
   at Lumafly.ViewModels.ModListViewModel.<ToggleApiCommand>g__DoActionWithWithErrorHandling|106_0(Func`1 Action) in D:\a\Lumafly\Lumafly\Lumafly\ViewModels\ModListViewModel.cs:line 576

**Comment by Ruttie2006** [comment]
Pirated versions of the game are not supported.
(Versões piratas do jogo não são suportadas. - Google translate)
