### ISSUE TITLE
Error while installing mod: Unauthorized Access

### ISSUE THREAD

**Issue by srpinho07** [TheMulhima/Lumafly#55]
### Scarab Version

v2.3.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

i open the scarab them i schearch for pale court themi click  to install and them is says "uma execução ocorrer enquanto installing or uninstalling pale court

### Expected Behaviour

i expected to install the mod

### Actual Behaviour

dont installed the mod

### Errors and Logs

Scarab Version: 2.3.0.0

System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Hollow Knight\Hollow Knight_Data\Managed\Assembly-CSharp.dll.v' is denied.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.Abstractions.FileWrapper.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Scarab.Services.Installer._InstallApi(ValueTuple`3 manifest) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 287
   at Scarab.Services.Installer.InstallApi() in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 258
   at Scarab.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 348
   at Scarab.Models.ModItem.OnInstall(IInstaller inst, Action`1 setProgress) in D:\a\Scarab\Scarab\Scarab\Models\ModItem.cs:line 214
   at Scarab.ViewModels.ModListViewModel.InternalModDownload(ModItem item, Func`3 downloader) in D:\a\Scarab\Scarab\Scarab\ViewModels\ModListViewModel.cs:line 824

**Comment by TheMulhima** [comment]
Hi, thanks for your report. The error can most likely be resolved by running the scarab app as an administrator (right-click on the executable and select "Run as administrator"). The error occurs because the application is unable to access the files in the game folder, so running as administrator should resolve the issue.
