### ISSUE TITLE
I cant activate custom knight

### ISSUE THREAD

**Issue by void-hearted** [TheMulhima/Lumafly#64]
### Scarab Version

v2.2.0.0

### Hollow Knight Version

v.1.5.78.11833

### Steps to Reproduce

try to activate custom knight in scarab

### Expected Behaviour

I expected that the mod would activate

### Actual Behaviour

It didnt activate and gave me this error: Unable to toggle Custom Knight.
Scarab was unable to access the file in the mods folder.

Scarab Version: 2.2.0.0

System.IO.IOException: Access to the path 'C:\Program Files (x86)\Steam\steamapps\common\Hollow Knight\hollow_knight_Data\Managed\Mods\Disabled\Custom Knight' is denied.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath, Boolean isCaseSensitiveRename)
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at Scarab.Services.Installer._Toggle(ModItem mod, Boolean enabled, ExistsModState state) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 186
   at Scarab.Services.Installer.Toggle(ModItem mod) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 152
   at Scarab.ViewModels.ModListViewModel.OnEnable(Object itemObj) in D:\a\Scarab\Scarab\Scarab\ViewModels\ModListViewModel.cs:line 768

### Errors and Logs

Unable to toggle Custom Knight.
Scarab was unable to access the file in the mods folder.

Scarab Version: 2.2.0.0

System.IO.IOException: Access to the path 'C:\Program Files (x86)\Steam\steamapps\common\Hollow Knight\hollow_knight_Data\Managed\Mods\Disabled\Custom Knight' is denied.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath, Boolean isCaseSensitiveRename)
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at Scarab.Services.Installer._Toggle(ModItem mod, Boolean enabled, ExistsModState state) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 186
   at Scarab.Services.Installer.Toggle(ModItem mod) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 152
   at Scarab.ViewModels.ModListViewModel.OnEnable(Object itemObj) in D:\a\Scarab\Scarab\Scarab\ViewModels\ModListViewModel.cs:line 768

**Comment by Acu1000** [comment]
Two things:
1. If you're using a cracked/pirated version of the game, it's probably the cause
2. If not, try running Scarab as administrator and see if it helps
