### ISSUE TITLE
Lumafly 无法访问 Mods 文件夹中的文件.无法安装或卸载Pale Court

### ISSUE THREAD

**Issue by XIAOZHIXIANGHOPE** [TheMulhima/Lumafly#84]
### Lumafly Version

v3.1.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

windows11笔记本电脑 下载pale court mod时报错

### Expected Behaviour

成功

### Actual Behaviour

Unable to installing or uninstalling Pale Court.Lumafly 无法访问 Mods 文件夹中的文件.无法安装或卸载Pale Court。Lumafly cannot access files in the Mods folder.

### Errors and Logs

Lumafly Version: 3.1.0.0

System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Lumafly.Util.HttpClientExt.DownloadBytesWithProgressAsync(HttpClient self, Uri uri, IProgress`1 progress, CancellationToken cts) in D:\a\Lumafly\Lumafly\Lumafly\Util\HttpClientExt.cs:line 89
   at Lumafly.Util.HttpClientExt.DownloadBytesWithProgressAsync(HttpClient self, Uri uri, IProgress`1 progress, CancellationToken cts) in D:\a\Lumafly\Lumafly\Lumafly\Util\HttpClientExt.cs:line 89
   at Lumafly.Services.Installer.DownloadFile(String uri, Action`1 setProgress) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 589
   at Lumafly.Services.Installer._Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 424
   at Lumafly.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 366
   at Lumafly.Models.ModItem.OnInstall(IInstaller inst, Action`1 setProgress) in D:\a\Lumafly\Lumafly\Lumafly\Models\ModItem.cs:line 206
   at Lumafly.ViewModels.ModListViewModel.InternalModDownload(ModItem item, Func`3 downloader) in D:\a\Lumafly\Lumafly\Lumafly\ViewModels\ModListViewModel.cs:line 966

**Comment by TheMulhima** [comment]
There seem to be multiple issues here and many reasons for it to happen. Could you open a ticket in the support channel of the modding discord to help diagnose this issue. The link to join the discord is: https://discord.gg/VDsg3HmWuB
