### ISSUE TITLE
无法进入游戏

### ISSUE THREAD

**Issue by WUFUDSM** [TheMulhima/Lumafly#96]
### Lumafly Version

1.14.0.0

### Hollow Knight Version

1.5

### Steps to Reproduce

Unable to launch the game

Lumafly Version: 3.2.0.0

System.ComponentModel.Win32Exception (5): 拒绝访问。
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at Lumafly.ViewModels.InfoViewModel._LaunchGame(Nullable`1 isVanilla) in D:\a\Lumafly\Lumafly\Lumafly\ViewModels\InfoViewModel.cs:line 70

### Expected Behaviour

加载我的游戏，加载mod

### Actual Behaviour

无法进入

### Errors and Logs

Unable to launch the game

Lumafly Version: 3.2.0.0

System.ComponentModel.Win32Exception (5): 拒绝访问。
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at Lumafly.ViewModels.InfoViewModel._LaunchGame(Nullable`1 isVanilla) in D:\a\Lumafly\Lumafly\Lumafly\ViewModels\InfoViewModel.cs:line 70

**Comment by Box074** [comment]
请尝试使用管理员权限启动Lumafly

若多次出现该问题，请说明 当前使用的平台（Steam, XBox Game, GOG，盗版等）以提供更好的解决方案
